stages:
  - Test
  - Publish
  - Deploy

.test:
  image: python:latest
  services:
  - postgres:latest

  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
  - pip install -r requirements.txt
  - python manage.py test natural_search/
  
.publish_docker:
  image: docker
  stage: Publish
  services:
    - docker:dind
  
  script:
    - docker login -p $PASSWORD_DOCKER -u $USER_DOCKER
    - docker build . -t filipekn4/nsapi
    - docker push filipekn4/nsapi

  tags:
    - docker

publish_development:
  extends: .publish_docker
  environment: development
  only: 
    - development

deploy:
  stage: Deploy

  script:
    - apt-get -y update
    - apt-get -y install sshpass
    - ls
    - ./deploy.sh $PASSWORD $IP
    - apt-get -y update
