version: '2'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=1234678
            - POSTGRES_USER=Igor
            - POSTGRES_DB=nome_projeto
        volumes:
            - ./ignore:/var/lib/postgresql/data
    web:
        environment:
            - POSTGRES_HOST=db
        image: filipekn4/nsapi:latest
        ports:
            - "8000:8000"
        command: ./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
