swagger: "2.0"
info:
  description: "Essa é a documentação da API do NaturalSearch. 
  
  NaturalSearch é um sistema que reúne dados a respeito de propostas de projetos e proponentes culturais a serem incentivados pelo Ministério da Cultura [MINC](http://www.cultura.gov.br/) por meio da [lei Rouanet](http://rouanet.cultura.gov.br/o-que-e/).
  
  Nele é possivel realizar uma pesquisa sobre as informações dos projetos e proponentes e visualizar o resultado em forma de grafo e suas conexões.  Você pode encontrar mais sobre o NaturalSearch em [https://fga-eps-mds.github.io/2018.2-NaturalSearch/](https://fga-eps-mds.github.io/2018.2-NaturalSearch/)."
  
  version: "1.0.0"
  title: "NaturalSearch API"
  contact:
    email: "equipe.naturalsearch@gmail.com"
host: "68.183.107.229:8000"
basePath: "/"

tags:
- name: "projetos : Dados relativos a Projetos"

schemes:
- "http"

produces:
  - application/json

paths:
  /projeto/:
    get:
      tags:
        - 'projetos : Dados relativos a Projetos'
      summary: Busca projetos dado uma combinação de valores diversos de pesquisa
      
      operationId: projeto_list
      
      parameters:
        - in: query
          name: limit
          description: Número de projetos a serem retornados
          required: false
          type: integer
          default: 100
          minimum: 1
          maximum: 100
          
        - in: query
          name: offset
          description: Número de paginação de resultados
          required: false
          type: integer
          default: 0
          minimum: 0
          
        - in: query
          name: PRONAC
          description: Número do PRONAC
          required: false
          type: string
          format: int64
          
        - in: query
          name: ano_projeto
          description: Ano em que o projeto foi apresentado em dois dígitos. Formato AA
          required: false
          type: string
          
        - in: query
          name: nome
          description: Nome do projeto (valor exato ou parcial)
          required: false
          type: string
          
        - in: query
          name: cgccpf
          description: Cgc/Cpf do proponente
          required: false
          type: string
          format: int64
          
        - in: query
          name: proponente
          description: Nome do proponente do projeto (valor exato ou parcial)
          required: false
          type: string
          
        - in: query
          name: segmento
          description: Código do Segmento do projeto
          required: false
          type: string
          
        - in: query
          name: area
          description: Código da Área do projeto
          required: false
          type: string
          
        - in: query
          name: UF
          description: 'Estado de origem no formato EE '
          required: false
          type: string
          
        - in: query
          name: municipio
          description: Cidade
          required: false
          type: string
          
        - in: query
          name: data_inicio
          description: Data de início no formato AAAA-MM-DD
          required: false
          type: string
          format: date
          
        - in: query
          name: data_termino
          description: Data de finalização no formato AAAA-MM-DD
          required: false
          type: string
          format: date
          
        - in: query
          name: mecanismo
          description: descrever
          required: false
          type: string
          
        - in: query
          name: enquadramento
          description: Artigo em que se enquadra
          required: false
          type: string
          
        - in: query
          name: valor_projeto
          description: Valor do projeto
          required: false
          type: number
          format: double
          
        - in: query
          name: valor_captado
          description: Valor captado
          required: false
          type: number
          format: double
          
        - in: query
          name: valor_proposta
          description: Valor da proposta
          required: false
          type: number
          format: double
          
        - in: query
          name: valor_solicitado
          description: Valor solicitado
          required: false
          type: number
          format: double
          
        - in: query
          name: valor_aprovado
          description: Valor aprovado
          required: false
          type: number
          format: double
        - in: query
          name: sort
          description: 'Ordenar a busca por um dos campos : PRONAC, ano_projeto, data_inicio, data_termino, valor_solicitado, outras_fontes, valor_captado, valor_proposta, valor_aprovado, valor_projeto. Formato: sort=CAMPO ou sort=CAMPO:asc ou ainda sort=CAMPO:desc. Padrão : ano_projeto:desc'
          required: false
          type: string
          
        - in: query
          name: format
          description: Formato de retorno
          enum:
            - json
          required: false
          type: string
          
      responses:
        '200':
          description: Operação bem-sucedida
          schema:
            type: array
            items:
              $ref: '#/definitions/Projeto'
              
        '404':
          description: Projetos com esses parâmetros não encontrados
          schema:
            $ref: '#/definitions/Error'
            
        '405':
          description: 'Parametros fornecidos invalidos '
          schema:
            $ref: '#/definitions/Error'
            
        '503':
          description: Erro interno
          schema:
            $ref: '#/definitions/Error'
  
  /proponente/:
    get:
      tags:
        - 'proponentes : Dados relativos a Proponentes'
      summary: Busca proponentes dado uma combinação de valores diversos de pesquisa
      
      operationId: proponente_list
      
      parameters:
        - in: query
          name: limit
          description: Número de proponentes a serem retornados
          required: false
          type: integer
          default: 100
          minimum: 1
          maximum: 100
          
        - in: query
          name: offset
          description: Número de paginação de resultados
          required: false
          type: integer
          default: 0
          minimum: 0
          
        - in: query
          name: nome
          description: Nome do proponente (valor exato ou parcial)
          required: false
          type: string
          
        - in: query
          name: cgccpf
          description: Cgc/Cpf do proponente
          required: false
          type: string
          format: int64
          
        - in: query
          name: proponente_id
          description: id de identificacao do proponente
          required: false
          type: string
          format: string
          
        - in: query
          name: municipio
          description: Cidade
          required: false
          type: string
          
        - in: query
          name: UF
          description: Estado
          required: false
          type: string
          
        - in: query
          name: tipo_pessoa
          description: Tipo de pessoa
          enum:
            - fisica
            - juridica
          required: false
          type: string
          
        - in: query
          name: sort
          description: 'Ordenar a busca por um dos campos : total_captado.Formato: sort=CAMPO ou sort=CAMPO:asc ou ainda sort=CAMPO:desc. Padrão : Internamente baseado no cgccpf'
          required: false
          type: string
          
        - in: query
          name: format
          description: Formato de retorno
          enum:
            - json
          required: false
          type: string
          
      responses:
        '200':
          description: Operação bem-sucedida
          schema:
            type: array
            items:
              $ref: '#/definitions/Proponente'
              
          headers:
            X-Rate-Limit-Limit:
              description: Número de requisições permitidas no período
              type: integer
              
            X-Rate-Limit-Remaining:
              description: Número de requisições restantes na janela de limite atual
              type: integer
              
            X-Rate-Limit-Reset:
              description: Tempo para que a janela de limite resete em segundos UTC epoch
              type: integer
              
            Retry-After:
              description: Segundos para tentar novamente ou a data http quando a janela de limite será resetada
              type: integer
              
            X-Total-Count:
              description: Número total de objetos que atendem seu critério de busca
              type: integer
              
        '404':
          description: Nenhum proponente com criterios fornecidos encontrados
          schema:
            $ref: '#/definitions/Error'
            
        '405':
          description: Parametros fornecidos inválidos
          schema:
            $ref: '#/definitions/Error'
            
        '503':
          description: Erro interno
          schema:
            $ref: '#/definitions/Error'
            
  '/proponente/{proponente_id}':
    get:
      tags:
        - 'proponentes : Dados relativos a Proponentes'
      summary: Busca proponentes dado um id fornecido
      
      operationId: proponente_detail
      
      parameters:
        - in: path
          name: proponente_id
          description: id do proponente
          required: true
          type: string
          
        - in: query
          name: format
          description: Formato de retorno
          enum:
            - json
          required: false
          type: string
          
      responses:
        '200':
          description: Operação bem-sucedida
          schema:
            $ref: '#/definitions/Proponente'
            
          headers:
            X-Rate-Limit-Limit:
              description: Número de requisições permitidas no período
              type: integer
              
            X-Rate-Limit-Remaining:
              description: Número de requisições restantes na janela de limite atual
              type: integer
              
            X-Rate-Limit-Reset:
              description: Tempo para que a janela de limite resete em segundos UTC epoch
              type: integer
              
            Retry-After:
              description: Segundos para tentar novamente ou a data http quando a janela de limite será resetada
              type: integer
              
        '404':
          description: Nenhum proponente com id fornecido encontrado
          schema:
            $ref: '#/definitions/Error'
            
        '405':
          description: Parametros fornecidos inválidos
          schema:
            $ref: '#/definitions/Error'
            
        '503':
          description: Erro interno
          schema:
            $ref: '#/definitions/Error'
            
definitions:

  Projeto:
    type: object
    properties:
    
      PRONAC:
        type: string
        format: int64
        
      ano_projeto:
        type: string
        
      nome:
        type: string
        
      cgccpf:
        type: string
        format: int64
        
      proponente:
        type: string
        
      segmento:
        type: string
        
      area:
        type: string
        
      UF:
        type: string
        
      municipio:
        type: string
        
      data_inicio:
        type: string
        format: date
        
      data_termino:
        type: string
        format: date
        
      mecanismo:
        type: string
        
      enquadramento:
        type: string
        
      valor_projeto:
        type: number
        format: double
        
      valor_captado:
        type: number
        format: double
        
      valor_proposta:
        type: number
        format: double
        
      valor_solicitado:
        type: number
        format: double
        
      valor_aprovado:
        type: number
        format: double
        
  Proponente:
    type: object
    properties:
    
      nome:
        type: string
        
      cgccpf:
        type: string
        format: int64
        
      responsavel:
        type: string
        
      tipo_pessoa:
        type: string
        
      UF:
        type: string
        
      municipio:
        type: string
        
      total_captado:
        type: number
        format: double
        
  Error:
    type: object
    properties:
    
      message:
        type: string
        
      code:
        type: string
        
      more_info:
        type: string